version: "3.9"
services:
  api:
    build:
      context: ./api/Handy.io
      dockerfile: Dockerfile
    container_name: handyio_api
    ports: 
      - "5000:80"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: handyio_client
    ports: 
      - "80:80"