export const apiUrl = "https://localhost:5001/services"
export const topServicesUrl = "/top-services"
export const serviceUrl = "/service/"
export const servicesUrl = "/services"
export const addServiceUrl = "/addService"
export const editServiceUrl = "/editService"
