export const apiUrl = "http://l212.115.110.219:5000/services"
export const topServicesUrl = "/top-services"
export const serviceUrl = "/service/"
export const servicesUrl = "/services"
export const addServiceUrl = "/addService"
export const editServiceUrl = "/editService"
