export const apiUrl = "http://localhost:5000"
export const topServicesUrl = "/topServices"
export const topServiceUrl = "/service"
export const servicesUrl = "/service"
export const addServiceUrl = "/addService"
export const editServiceUrl = "/editService"
